---
- hosts: worker
  become: true
  #gather_facts: false
  tasks:
  - name: Copy /etc/kubernetes/admin.conf to user home kube config
    shell: cat /etc/hostname
    register: kube_hostname

  - name: copy command
    copy:
    shell: cat kube_hostname.stdout_lines > /tmp/kube_join
